/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HostRouteImport } from './routes/host'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ChatsIdRouteImport } from './routes/chats.$id'
import { Route as HostNewRouteImport } from './routes/host.new'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatsRoute,
} as any)
const HostNewRoute = HostNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HostRoute,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/chats': typeof ChatsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/chats/$id': typeof ChatsIdRoute
  '/host/new': typeof HostNewRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/chats': typeof ChatsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/chats/$id': typeof ChatsIdRoute
  '/host/new': typeof HostNewRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/chats': typeof ChatsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/chats/$id': typeof ChatsIdRoute
  '/host/new': typeof HostNewRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/chats'
    | '/favorites'
    | '/host'
    | '/login'
    | '/payments'
    | '/profile'
    | '/search'
    | '/chats/$id'
    | '/host/new'
    | '/listing/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/chats'
    | '/favorites'
    | '/host'
    | '/login'
    | '/payments'
    | '/profile'
    | '/search'
    | '/chats/$id'
    | '/host/new'
    | '/listing/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/chats'
    | '/favorites'
    | '/host'
    | '/login'
    | '/payments'
    | '/profile'
    | '/search'
    | '/chats/$id'
    | '/host/new'
    | '/listing/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  HostRoute: typeof HostRouteWithChildren
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  ListingIdRoute: typeof ListingIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/host/new': {
      id: '/host/new'
      path: '/new'
      fullPath: '/host/new'
      preLoaderRoute: typeof HostNewRouteImport
      parentRoute: typeof HostRoute
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatsRouteChildren {
  ChatsIdRoute: typeof ChatsIdRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsIdRoute: ChatsIdRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

interface HostRouteChildren {
  HostNewRoute: typeof HostNewRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostNewRoute: HostNewRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  ChatsRoute: ChatsRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  HostRoute: HostRouteWithChildren,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  ListingIdRoute: ListingIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
